# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# User.create!(email: 'test@gmail.com',password: 'password')
# City.create!(name: 'Lahore')
# City.create!(name: 'Karachi')
# City.create!(name: 'Rawalpindi')
# Discipline.create!(name:'Engineering',description:'Engineering and technology is based on the application of existing technology within a field of engineering through the use of basic engineering principles and technical skills. As such, bachelor and master programmes in engineering and technology focus primarily on the applied aspects of science to equip graduates with practical technical skills in product improvement, manufacturing, construction or engineering operational functions.Universities provide a wide offer of Masters of Science (M.Sc.) in engineering and technology that keeps on growing and resulting in extensive specialisations and technological development. Studying engineering equips students with practical skills to acquire and apply scientific, mathematical, economic, social and practical knowledge to design and build structures, machines, devices, systems, materials and processes that safely serve as solutions to the needs of society. Through hands-on training, students are encouraged to come up with creative applications of scientific principles.Careers in engineering and technology are as diverse as the subject they specialise in. Graduates can find work as software engineers, computer programmers, computer system analysts, electrical engineers, mechanical engineers, nuclear engineers, civil engineers, industrial designers, aerospace engineers, and more.')
Discipline.create!(name:'Business',description:'Engineering and technology is based on the application of existing technology within a field of engineering through the use of basic engineering principles and technical skills. As such, bachelor and master programmes in engineering and technology focus primarily on the applied aspects of science to equip graduates with practical technical skills in product improvement, manufacturing, construction or engineering operational functions.Universities provide a wide offer of Masters of Science (M.Sc.) in engineering and technology that keeps on growing and resulting in extensive specialisations and technological development. Studying engineering equips students with practical skills to acquire and apply scientific, mathematical, economic, social and practical knowledge to design and build structures, machines, devices, systems, materials and processes that safely serve as solutions to the needs of society. Through hands-on training, students are encouraged to come up with creative applications of scientific principles.Careers in engineering and technology are as diverse as the subject they specialise in. Graduates can find work as software engineers, computer programmers, computer system analysts, electrical engineers, mechanical engineers, nuclear engineers, civil engineers, industrial designers, aerospace engineers, and more.')
Discipline.create!(name:'Law',description:'Engineering and technology is based on the application of existing technology within a field of engineering through the use of basic engineering principles and technical skills. As such, bachelor and master programmes in engineering and technology focus primarily on the applied aspects of science to equip graduates with practical technical skills in product improvement, manufacturing, construction or engineering operational functions.Universities provide a wide offer of Masters of Science (M.Sc.) in engineering and technology that keeps on growing and resulting in extensive specialisations and technological development. Studying engineering equips students with practical skills to acquire and apply scientific, mathematical, economic, social and practical knowledge to design and build structures, machines, devices, systems, materials and processes that safely serve as solutions to the needs of society. Through hands-on training, students are encouraged to come up with creative applications of scientific principles.Careers in engineering and technology are as diverse as the subject they specialise in. Graduates can find work as software engineers, computer programmers, computer system analysts, electrical engineers, mechanical engineers, nuclear engineers, civil engineers, industrial designers, aerospace engineers, and more.')
Discipline.create!(name:'Computer',description:'Engineering and technology is based on the application of existing technology within a field of engineering through the use of basic engineering principles and technical skills. As such, bachelor and master programmes in engineering and technology focus primarily on the applied aspects of science to equip graduates with practical technical skills in product improvement, manufacturing, construction or engineering operational functions.Universities provide a wide offer of Masters of Science (M.Sc.) in engineering and technology that keeps on growing and resulting in extensive specialisations and technological development. Studying engineering equips students with practical skills to acquire and apply scientific, mathematical, economic, social and practical knowledge to design and build structures, machines, devices, systems, materials and processes that safely serve as solutions to the needs of society. Through hands-on training, students are encouraged to come up with creative applications of scientific principles.Careers in engineering and technology are as diverse as the subject they specialise in. Graduates can find work as software engineers, computer programmers, computer system analysts, electrical engineers, mechanical engineers, nuclear engineers, civil engineers, industrial designers, aerospace engineers, and more.')
